### ISSUE TITLE
Question about the xml parser

### ISSUE THREAD

**Issue by stzer** [oddball/ipxact2systemverilog#10]
Hello. I'm using your project and I have a question. It would be nice if you can help me.
The main problem is that the parser fails if xml file has no attributes (for example, a memoryMap). Is there any way to make the parser work even if there are no attributes in a file?

Thank you for answer.

**Comment by oddball** [comment]
Could you paste an example of a file that fails? Also the error message that you get

**Comment by oddball** [comment]
Closing since not heard from OP
