### ISSUE TITLE
bad interpreter

### ISSUE THREAD

**Issue by snarum-NIS** [oddball/ipxact2systemverilog#14]
After installing, I get the following error when trying to run:

-bash: /usr/bin/ipxact2systemverilog: .: bad interpreter: Permission denied

The executable has the following permissions:
-rwxr-xr-x. 1 root root 226 Mar  2 13:31 /usr/bin/ipxact2systemverilog*

Both python 2.7.5 and 3.6.3 are installed and working.

Any help?

**Comment by oddball** [comment]
Hi!
could you post what 
```
more /usr/bin/ipxact2systemverilog 
``` 
say? At least the first lines?
what does 
```
python2.7 /usr/bin/ipxact2systemverilog --help
python3.6 /usr/bin/ipxact2systemverilog --help
``` 
say?

**Comment by oddball** [comment]
did you install it with pip3 or pip2 ?

**Comment by snarum-NIS** [comment]
I was able to do a complete remove and reinstall of the software.  Now it runs correctly.  Sorry I forgot to close this issue.
