### ISSUE TITLE
generate c code

### ISSUE THREAD

**Issue by oddball** [oddball/ipxact2systemverilog#15]
Would like this package to generate C code. If someone could provide an example ipxact xml file and corresponding c code, it should be easy enough for me to add generation of C code.

**Comment by EdwinElshoud** [comment]
Hi @oddball,

Maybe a little late, but I have created a fork and implemented a generator for a C header file. It is a macro based header file to get to the register fields.

[ipxact2systemverilog fork](https://github.com/EdwinElshoud/ipxact2systemverilog)

Kind regards,
Edwin

**Comment by oddball** [comment]
Hi @EdwinElshoud! Nice!

Feel free to make a PR back to this repo, and I will be happy to review it!

Best regards

**Comment by oddball** [comment]
https://github.com/oddball/ipxact2systemverilog/pull/35

@EdwinElshoud Thanks for this! 👍

Added a compilation and execution of your example.c on CircleCI

Released https://pypi.org/project/ipxact2systemverilog/

Feel free to check it out, and let me know if something is wrong!
