### ISSUE TITLE
ipxact2hdlCommon.py returnRstTitle returns hardcoded string iso addressBlock.name

### ISSUE THREAD

**Issue by wolfgang-blaszczyk** [oddball/ipxact2systemverilog#43]
If there are several .xml files in a map, describing registers, after running ipxact2rst, each .rst file begins with : 
====================
Register description
====================

Registers
---------

It would be an improvement, if instead we could have the real name of the register, as describe in the xml document at:
      <spirit:addressBlock>
        <spirit:name>fpi_registers</spirit:name>   <== this name (fpi_registers) should be the header of the .rst file.

**Comment by oddball** [comment]
This is unclear to me. You cannot point out a filesystem directory  ( which is what I assume you mean with ma)

If you do something like
```bash
 ipxact2rst --srcFile example/input --destDir
 ``` 
 you will get an error
 ``` 
 IsADirectoryError: [Errno 21] Is a directory: 'example/input'
 ```
 
 Please elaborate

**Comment by wolfgang-blaszczyk** [comment]
I dont know how to explain it better tan this:
I have a folder with several .xml files, describing registers.
When I run ipxact2rst on those files, the result are  several .rst files, each starting with a hardcoded header generated by the

class rstAddressBlock(addressBlockClass):

    def returnRstTitle(self):
        r = ''
        r += "====================\n"
        r += "Register description\n"
        r += "====================\n\n"
        return r

    def returnRstSubTitle(self):
        r = ''
        r += "Registers\n"
        r += "---------\n\n"
        return r

When running make html from those files, I get in the index.html in the contents, not the name of the registers, but for each register the same tittle : Register description.

<ul>
<li class="toctree-l1"><a class="reference internal" href="registermaps/conf_registers.html">Register description</a></li>
<li class="toctree-l1"><a class="reference internal" href="registermaps/debug_registers.html">Register description</a></li>
<li class="toctree-l1"><a class="reference internal" href="registermaps/fpi_registers.html">Register description</a></li>

.... 
Instead I would like to have Register description of each list item to be the name of the register, read from the xml 

      <spirit:addressBlock>
        <spirit:name>conf_registers</spirit:name>  <=== this name should be in the header of the rst file

**Comment by vermaete** [comment]
@wolfgang-blaszczyk Could you check if my fork is fixing your issue before doing a merge request to Oddball.
https://github.com/vermaete/ipxact2systemverilog

You will still have the issue that the generated documentation (MarkDown and ResturcturedText) is starting with upper header.
This still can have issues if you want to collect the generated files into one top document.
To be fixed later :-)

br

**Comment by oddball** [comment]
@wolfgang-blaszczyk, does the last release fix this issue?
